// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPJjyCWGAPhhgAw9bHBeQT7H5Aizj4U6g',
    appId: '1:643726625820:web:ef2203543893eb1c7723d9',
    messagingSenderId: '643726625820',
    projectId: 'currency-rate-calculator-b3347',
    authDomain: 'currency-rate-calculator-b3347.firebaseapp.com',
    storageBucket: 'currency-rate-calculator-b3347.firebasestorage.app',
    measurementId: 'G-KLV55V5VXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRFaC1aWXBBRwk6YtuZbFrOfk6CP0e7BE',
    appId: '1:643726625820:android:8fbaf3bcbb46105c7723d9',
    messagingSenderId: '643726625820',
    projectId: 'currency-rate-calculator-b3347',
    storageBucket: 'currency-rate-calculator-b3347.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDahUXj-nZBPua_d1sugEtnNB4v59M3po8',
    appId: '1:643726625820:ios:54b775a701315cb77723d9',
    messagingSenderId: '643726625820',
    projectId: 'currency-rate-calculator-b3347',
    storageBucket: 'currency-rate-calculator-b3347.firebasestorage.app',
    iosBundleId: 'com.example.currencyRateCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDahUXj-nZBPua_d1sugEtnNB4v59M3po8',
    appId: '1:643726625820:ios:54b775a701315cb77723d9',
    messagingSenderId: '643726625820',
    projectId: 'currency-rate-calculator-b3347',
    storageBucket: 'currency-rate-calculator-b3347.firebasestorage.app',
    iosBundleId: 'com.example.currencyRateCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPJjyCWGAPhhgAw9bHBeQT7H5Aizj4U6g',
    appId: '1:643726625820:web:b8a70811ef00ae3b7723d9',
    messagingSenderId: '643726625820',
    projectId: 'currency-rate-calculator-b3347',
    authDomain: 'currency-rate-calculator-b3347.firebaseapp.com',
    storageBucket: 'currency-rate-calculator-b3347.firebasestorage.app',
    measurementId: 'G-LGYYQEX7BZ',
  );
}
